CREATE TABLE bebida (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(80) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL,
    estoque INTEGER NOT NULL,
    foto VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;